# Generated by Django 2.2.2 on 2019-06-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysimplemodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mysimplemodel',
            name='row',
            field=models.BooleanField(null=True),
        ),
    ]
