# Generated by Django 2.2.2 on 2019-06-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_auto_20190630_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysimplemodel',
            name='row',
        ),
    ]
