# Generated by Django 2.2.2 on 2019-07-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_remove_mysimplemodel_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('dates', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
